version: '3.9' 
services:
  camera:
    image: rliebert/jetson_galactic:opencv_4.4
    volumes:
      - /dev/video0:/dev/video0
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/argus_socket:/tmp/argus_socket
    networks: "host"
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    privileged: true
    command: "python3 /fusion_ws/scr/pi_cam_v2_pub.py"
  box_detection:
    image: rliebert/jetson_galactic:opencv_4.4
    depends_on:
      - camera
    networks: "host"
    runtime: nvidia
    privileged: true
    command: "python3 /fusion_ws/scr/box_detection.py"
  uros_agent:
    image: microros/micro-ros-agent:galactic
    depends_on:
      - imu_node
    networks: "host"
    runtime: nvidia
    command: "udp4 -p 8888"
  imu_node:
    image: rliebert/galactic_uros:latest
    networks: "host"
    runtime: nvidia
    command: "python3 /fusion_ws/scr/imu_node.py"
  fusion_node:
    image: rliebert/jetson_galactic:latest
    depends_on:
      - imu_node
      - box_detection
    networks: "host"
    runtime: nvidia
    command: "python3 /fusion_ws/scr/fusion.py"
  logger:
    image: rliebert/jetson_galactic:latest
    depends_on:
      - fusion_node
    networks: "host"
    runtime: nvidia
    command: "python3 /fusion_ws/scr/export_to_csv.py"